# BIRD 2 — vetor de distância (RIP), roteador 3 (o do desvio)
log stderr all;
router id 10.0.40.13;

protocol device { }
protocol direct { ipv4; interface "eth*"; }
protocol kernel { ipv4 { export all; }; learn; }

protocol rip {
  ipv4 { import all; export all; };
  interface "*" { };
}
