# BIRD 2 — vetor de distância (RIP), roteador 1
log stderr all;
router id 10.0.10.254;          # identidade única deste roteador

protocol device { }

# Publica as redes diretamente conectadas
protocol direct { ipv4; interface "eth*"; }

# Escreve no kernel o que o RIP aprender, e lê o que já existe
protocol kernel { ipv4 { export all; }; learn; }

protocol rip {
  ipv4 { import all; export all; };
  interface "*" { };            # RIP em todas as pernas
}
